apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi1-depl
spec:
  replicas: 0
  selector:
    matchLabels:
      app: webapi1
  template:
    metadata:
      labels:
        app: webapi1
    spec:
      containers:
      - name: webapi1
        image: riverlazuli/webapi1
---
apiVersion: v1
kind: Service
metadata:
  name: webapi1-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: webapi1
  ports:
  - name: webapi1
    protocol: TCP
    port: 80
    targetPort: 80