apiVersion: v1
kind: Service
metadata:
  name: webapi1npservice-srv
spec:
  type: NodePort
  selector:
    app: webapi1
  ports:
    - name: webapi1
      protocol: TCP
      port: 80
      targetPort: 80